Apple OAuth Client Secret 추가
SimLeeTag/homework-backend pull request #8
Opened 2022-05-02 14:16 UTC by suhyunsim

### 요구 사항
- 기존 apple oauth attribute에서 누락됐던 client secret 추가

### 구현 과정
- Apple Client Secret을 만들기 위해서 private key를 요청
    - private key를 생성하기 위해 Bouncy Castle Provider 의존성 추가
- private key를 이용해 Client Secret을 생성하고 해당 내용을 포함해 Apple OAuth Provider를 구현

### 피드백 및 리뷰 포인트
- sub module에 관련 민감정보를 설정하면서 혹시 현식군 레포에서도 제대로 작동하는지 확인할 필요가 있을 것 같습니다!

2022-05-04 05:30 UTC, hsik0225 requested changes
기능 개발 수고하셨습니다 😄
간단하게 제 생각을 코멘트로 남겨놓았으니 확인부탁드릴게요!

2022-05-04 05:30 UTC, hsik0225 commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +        return JWT.create()
OAuthJwt 클래스에서 토큰을 만들지 않고, 현재 클래스에서 토큰을 만든 이유가 궁금합니다. 😀
제가 보기엔 OAuthJwt가 토큰을 만들 책임을 갖고 있지만, AppleOAuthProvider가 그 역할을 가져간 것 같아요.

### AppleOAuthProvider가 토큰을 만들기 위한 변수들을 가지고 있기 때문일까요?
만약 그렇다면 OAuthJwt에 토큰 생성에 필요한 변수들을 @Value를 사용하여 필드로 받도록 하거나 OAuthAttribute를 OAuthJwt#makeClientSecret()에 파라미터로 넘기는 건 어떨까요?

2022-05-04 05:30 UTC, hsik0225 commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +    @Value("${apple.team.id}")
해당 설정은 OAuth 관련 설정이니 `application.properties`에 `oauth.attribute.apple.team.id`로 작성하여 받아야 할 것 같습니다

2022-05-04 05:30 UTC, hsik0225 commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +    private String CLIENT_ID;
properties에서 받아오는 설정 값은 변하지 않는 상수이긴 하니 `대문자 스네이크 케이스`로 적는 건가요?
잘 몰라서 물어봅니다 🙂

2022-05-04 05:30 UTC, hsik0225 commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +                .withAudience("https://appleid.apple.com")
Apple 설정은 properties에서 관리하고 있으니 이 친구도 설정에서 관리하도록 하는 건 어떨까요?

2022-05-04 05:30 UTC, hsik0225 commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +        Date expirationDate = Date.from(LocalDateTime.now().plusDays(30).atZone(ZoneId.systemDefault()).toInstant());
`30`이라는 매직넘버를 설정 파일에서 관리하면 의미가 명확해져서 더 좋을 것 같아요!

2022-05-08 06:46 UTC, suhyunsim commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +    private String CLIENT_ID;
특별히 어떤 컨벤션을 따른건 아닌데 설정 값이라 대문자 스네이크 케이스로 적었습니다. 혹시 변경이 필요할까요?

2022-05-08 06:46 UTC, suhyunsim commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +                .withAudience("https://appleid.apple.com")
반영했습니다!

2022-05-08 06:46 UTC, suhyunsim commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +        Date expirationDate = Date.from(LocalDateTime.now().plusDays(30).atZone(ZoneId.systemDefault()).toInstant());
반영했습니다!

2022-05-08 06:47 UTC, suhyunsim commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +    @Value("${apple.team.id}")
반영했습니다! 다른 value값들도 prefix를 `oauth.attribute.`으로 수정하겠습니다!

2022-05-08 08:04 UTC, suhyunsim commented on src/main/java/com/simleetag/homework/domain/oauth/AppleOAuthProvider.java
> +        return JWT.create()
해당 부분을 따로 분리하는게(결국 OAuthJwt도 kakao와 apple로 분리해야해서) 너무 수고롭진 않을까 고민했는데 결국 외부 영향을 적게 받기 위해서 필요한 작업일 듯 하네요! 일단은 추후 리팩토링에 반영할 수 있도록 해당 클래스에 남겨놓고 있겠습니다!! 리뷰 감사해요!

2022-05-09 06:03 UTC, hsik0225 approved these changes
코멘트 및 수정하신 부분 확인했습니다.
수고하셨어요!

2022-05-09 06:26 UTC, merged